### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AIsquare** [uber-research/DeepPruner#29]
I am trying to train your model on colab with only "KITTI best" pretrained weights and with only KITTI 2015. after solving some of the errors. I get stuck on this error:
**I am passing !python finetune_kitti.py --loadmodel /content/DeepPruner/deeppruner/DeepPruner-best-kitti.tar --train_datapath_2015 /content/DeepPruner/kitti_2015/training --val_datapath_2015 /content/DeepPruner/kitti_2015/testing**

finetune_kitti.py: loading model...
finetune_kitti.py: Number of model parameters: 7390142
finetune_kitti.py: learning rate = 0.00010
Traceback (most recent call last):
  File "finetune_kitti.py", line 218, in <module>
    main()
  File "finetune_kitti.py", line 198, in main
    for batch_idx, (imgL_crop, imgR_crop, disp_crop_L) in enumerate(TrainImgLoader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/content/DeepPruner/deeppruner/dataloader/kitti_loader.py", line 53, in __getitem__
    left_disp = self.left_disp[index]
IndexError: list index out of range

**Comment by HexaWarriorW** [comment]
Make sure **split KITTI Stereo 2015 training dataset into "training" (160 pairs) and "validation" (40 pairs).** Then change all "*png" to "*_10.png" in "dataloader/kitti_collector.py". This works for me.

**Comment by ShivamDuggal4** [comment]
Looks like the issue has been answered. Please feel free to reopen if the issue still persists.
